// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://trwxtwgelkcokkvujblz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRyd3h0d2dlbGtjb2trdnVqYmx6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIyMzQ5OTksImV4cCI6MjA3NzgxMDk5OX0.IWHCjcGMLphVOPqcrS5abt3A5YolepmGYSQUMPrPy_U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});